version: '3'
services:
  slidev:
    container_name: slidev
    image: myppt
    volumes:
      - ./markdown:/slidev
    ports:
      - 3030:3030
    environment:
      NPM_MIRROR: https://registry.npmmirror.com
    restart: always
